In [41]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
import pickle
import numpy as np

In [42]:
TEMP_FILES_DIRECTORY = "./TEMP/"

In [55]:
X = np.load(TEMP_FILES_DIRECTORY + 'training_X.npy')
Y = np.load(TEMP_FILES_DIRECTORY + 'training_Y.npy')

X = np.asarray(X)
Y = np.asarray(Y)

X = X/255.0

In [58]:
print(X[0])
for i in Y[:5]:
    print(i)

[[[0.39215686]
  [0.37647059]
  [0.37254902]
  ...
  [0.3372549 ]
  [0.3372549 ]
  [0.34509804]]

 [[0.39215686]
  [0.32156863]
  [0.31372549]
  ...
  [0.30196078]
  [0.30196078]
  [0.36078431]]

 [[0.37647059]
  [0.34117647]
  [0.30196078]
  ...
  [0.31764706]
  [0.31764706]
  [0.36470588]]

 ...

 [[0.36862745]
  [0.35294118]
  [0.46666667]
  ...
  [0.35686275]
  [0.31764706]
  [0.27058824]]

 [[0.50196078]
  [0.48235294]
  [0.63137255]
  ...
  [0.39607843]
  [0.40784314]
  [0.39607843]]

 [[0.48627451]
  [0.53333333]
  [0.61960784]
  ...
  [0.45098039]
  [0.45882353]
  [0.36470588]]]
0
2
3
3
2


In [59]:
CATEGORIES = ["CAT", "CHICKEN", "DOG", "HORSE"]

CATEGORIES_TO_TRAIN = ["CAT", "CHICKEN", "DOG", "HORSE"]

training_sets = []

for category in CATEGORIES_TO_TRAIN:
    this_category_Y = []
    this_category_id = CATEGORIES.index(category)

    for category_id in Y:
        
        if category_id == this_category_id:
            this_category_Y.append(1)
        else:
            this_category_Y.append(0)
    
    this_category_Y = np.asarray(this_category_Y)

    new_training_set = [category, 0, this_category_Y]   # 0 is a placeholder to replace with the model in the next step
    training_sets.append(new_training_set)
    #print(category)
    #print(this_category_Y)


In [60]:
for category, model, category_Y in training_sets:
    print(category)
    for y in category_Y[:5]:
        print(y, end=' - ')
    print()
    

CAT
1 - 0 - 0 - 0 - 0 - 
CHICKEN
0 - 0 - 0 - 0 - 0 - 
DOG
0 - 1 - 0 - 0 - 1 - 
HORSE
0 - 0 - 1 - 1 - 0 - 


In [69]:

for item in training_sets:
    new_model = Sequential()
    new_model.add(Conv2D(64,(3,3),input_shape = X.shape[1:]))
    new_model.add(Activation("relu"))
    new_model.add(MaxPooling2D(pool_size=(2,2)))

    new_model.add(Conv2D(64,(3,3)))
    new_model.add(Activation("relu"))
    new_model.add(MaxPooling2D(pool_size=(2,2)))

    new_model.add(Flatten())
    new_model.add(Dense(64))

    new_model.add(Dense(1))
    new_model.add(Activation('sigmoid'))

    training_sets[training_sets.index(item)][1] = new_model


In [61]:
test_model = Sequential()

test_model.add(Conv2D(64,(3,3),input_shape = X.shape[1:]))
test_model.add(Activation("relu"))
test_model.add(MaxPooling2D(pool_size=(2,2)))

test_model.add(Conv2D(64,(3,3)))
test_model.add(Activation("relu"))
test_model.add(MaxPooling2D(pool_size=(2,2)))

test_model.add(Flatten())
test_model.add(Dense(64))

test_model.add(Dense(1))
test_model.add(Activation('sigmoid'))

test_model.compile(loss="binary_crossentropy",optimizer="adam",metrics=['accuracy'])

test_model.fit(X, training_sets[3][2], batch_size=32, epochs=2, validation_split=0.1)

Epoch 1/2
17/17 [==============================] - 11s 622ms/step - loss: 0.7754 - accuracy: 0.7019 - val_loss: 0.5413 - val_accuracy: 0.7500
Epoch 2/2
17/17 [==============================] - 10s 609ms/step - loss: 0.5072 - accuracy: 0.7685 - val_loss: 0.4570 - val_accuracy: 0.7833


In [64]:
test_prediction = test_model.predict(X)
print(test_prediction)

[[0.18431395]
 [0.25649616]
 [0.13681895]
 [0.13083059]
 [0.04829708]
 [0.43616343]
 [0.10443076]
 [0.09022343]
 [0.18209869]
 [0.09013161]
 [0.17039931]
 [0.26817292]
 [0.36091396]
 [0.19325495]
 [0.12913927]
 [0.0847722 ]
 [0.25807297]
 [0.43489453]
 [0.08806261]
 [0.12422848]
 [0.14921841]
 [0.16798973]
 [0.06835511]
 [0.13164946]
 [0.27418765]
 [0.37421107]
 [0.09760717]
 [0.6194181 ]
 [0.15614435]
 [0.3165917 ]
 [0.18768784]
 [0.27590168]
 [0.1758925 ]
 [0.10781926]
 [0.10110003]
 [0.11104512]
 [0.32784194]
 [0.1631448 ]
 [0.23093116]
 [0.23570207]
 [0.06079316]
 [0.12643841]
 [0.05116579]
 [0.70902455]
 [0.10794216]
 [0.2686702 ]
 [0.5515251 ]
 [0.15328717]
 [0.15470138]
 [0.104009  ]
 [0.11257705]
 [0.3191212 ]
 [0.10397226]
 [0.1073412 ]
 [0.06980893]
 [0.04297188]
 [0.21656111]
 [0.09400955]
 [0.23342302]
 [0.17342967]
 [0.12291232]
 [0.08095434]
 [0.22561815]
 [0.05814585]
 [0.10873893]
 [0.17209527]
 [0.11801839]
 [0.02637202]
 [0.20336723]
 [0.04320085]
 [0.09394044]
 [0.09

In [70]:
for item in training_sets:
    index = training_sets.index(item)
    training_sets[index][1].compile(loss="binary_crossentropy",optimizer="adam",metrics=['accuracy'])

In [71]:
for category, model, category_Y in training_sets:
    index = training_sets.index([category, model, category_Y])

    training_sets[index][1].fit(X, category_Y, batch_size=64, epochs=5, validation_split=0.1)

Epoch 1/5
9/9 [==============================] - 10s 1s/step - loss: 1.4886 - accuracy: 0.6185 - val_loss: 0.9736 - val_accuracy: 0.6667
Epoch 2/5
9/9 [==============================] - 9s 1s/step - loss: 0.5871 - accuracy: 0.7593 - val_loss: 0.6466 - val_accuracy: 0.6667
Epoch 3/5
9/9 [==============================] - 9s 1s/step - loss: 0.4988 - accuracy: 0.7593 - val_loss: 0.6058 - val_accuracy: 0.7000
Epoch 4/5
9/9 [==============================] - 9s 1s/step - loss: 0.4603 - accuracy: 0.7759 - val_loss: 0.5892 - val_accuracy: 0.7000
Epoch 5/5
9/9 [==============================] - 9s 1s/step - loss: 0.3998 - accuracy: 0.7981 - val_loss: 0.5717 - val_accuracy: 0.7167
Epoch 1/5
9/9 [==============================] - 10s 1s/step - loss: 1.0208 - accuracy: 0.5019 - val_loss: 0.6549 - val_accuracy: 0.8000
Epoch 2/5
9/9 [==============================] - 9s 1s/step - loss: 0.6106 - accuracy: 0.7444 - val_loss: 0.5278 - val_accuracy: 0.8000
Epoch 3/5
9/9 [==============================]

In [75]:
for category_name, model, category_Y in training_sets:
    index = training_sets.index([category_name, model, category_Y])
    training_sets[index][1].save('SavedModels/' + category_name)

INFO:tensorflow:Assets written to: SavedModels/CAT\assets
INFO:tensorflow:Assets written to: SavedModels/CHICKEN\assets
INFO:tensorflow:Assets written to: SavedModels/DOG\assets
INFO:tensorflow:Assets written to: SavedModels/HORSE\assets


In [76]:
test_prediction = training_sets[0][1].predict(X)
print(test_prediction)

[[3.64028960e-01]
 [1.17211938e-02]
 [2.74106622e-01]
 [3.33832800e-01]
 [4.84816790e-01]
 [7.61848986e-02]
 [5.86750865e-01]
 [9.40451324e-02]
 [8.16018879e-02]
 [3.69525194e-01]
 [1.99511349e-01]
 [1.28242821e-01]
 [1.75810188e-01]
 [2.16409802e-01]
 [2.98196077e-02]
 [3.32702458e-01]
 [7.75085986e-02]
 [6.00920022e-02]
 [1.53148144e-01]
 [4.17631656e-01]
 [6.20419860e-01]
 [5.15952587e-01]
 [5.80893755e-01]
 [1.48001134e-01]
 [3.87677252e-02]
 [3.01864147e-02]
 [5.74907362e-02]
 [4.45085764e-03]
 [9.72986221e-03]
 [2.43117481e-01]
 [2.21359968e-01]
 [3.73750687e-01]
 [2.73034036e-01]
 [3.70004088e-01]
 [2.85605192e-01]
 [2.61934996e-02]
 [2.89501250e-02]
 [2.69199312e-01]
 [1.86339557e-01]
 [2.17498690e-01]
 [4.01159406e-01]
 [3.96128535e-01]
 [6.09783590e-01]
 [3.35529447e-03]
 [3.40023756e-01]
 [3.99934649e-02]
 [4.66122925e-02]
 [1.77200347e-01]
 [1.17158532e-01]
 [4.95399356e-01]
 [1.59181684e-01]
 [1.23839319e-01]
 [5.72639704e-02]
 [3.05029720e-01]
 [3.64613533e-02]
 [3.664030